# Generated by Django 4.1 on 2022-10-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_alter_center_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='center',
        ),
        migrations.AddField(
            model_name='area',
            name='center',
            field=models.ManyToManyField(to='centers.center'),
        ),
    ]
